all: client primaryServer secondaryServer
cleanFiles:
	rm client.class primaryServer.class secondaryServer.class
client:	
	javac client.java
primaryServer:	
	javac primaryServer.java
secondaryServer:	
	javac secondaryServer.java
